name: 陈豆豆之家
author: 陈哈哈
url: https://cgyly.github.io/testpinghsu-jekyll/
baseurl: 
resume_site: 
description: 
github_username: 
github: 
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : ebe0a57efec564c60e2c
    clientSecret : 7d484241f9316b10fe9b36ea23638d3419676ca1
    repo : pages
    owner : Cgyly
    admin :  [ly,cgy]
